# Preprocess TSMC2014 datasets

This notebook converts the raw TSMC2014 New York and Tokyo check-in files into CSV event datasets with artificial event IDs, coordinates, minutes since the first event, absolute occurrence time from the raw UTC timestamp, and event type.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == "Notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

sys.path.insert(0, str(PROJECT_ROOT / "Source"))

from preprocess_tsmc2014 import preprocess_all

In [2]:
raw_dir = PROJECT_ROOT / "Data" / "Raw"
output_dir = PROJECT_ROOT / "Data" / "Preprocessed"

output_paths = preprocess_all(raw_dir=raw_dir, output_dir=output_dir)
output_paths

[PosixPath('/Users/piotr/Praca/Nauka/publikacje/SNNs_ST_Patterns/Experiments_software/Data/Preprocessed/dataset_TSMC2014_NYC_preprocessed.csv'),
 PosixPath('/Users/piotr/Praca/Nauka/publikacje/SNNs_ST_Patterns/Experiments_software/Data/Preprocessed/dataset_TSMC2014_TKY_preprocessed.csv')]

In [3]:
import pandas as pd

for path in output_paths:
    data = pd.read_csv(path)
    print(path.name)
    display(data.head())
    print(data.shape)
    print()

dataset_TSMC2014_NYC_preprocessed.csv

,Event_ID,longitude,latitude,timestamp,Occurrence_time,Event_type
0,1,-74.002581,40.719810,0.000000,Tue Apr 03 18:00:09 +0000 2012,Arts & Crafts Store
1,2,-74.044170,40.606800,0.266667,Tue Apr 03 18:00:25 +0000 2012,Bridge
2,3,-73.883070,40.716162,2.250000,Tue Apr 03 18:02:24 +0000 2012,Home (private)
3,4,-73.982519,40.745164,2.533333,Tue Apr 03 18:02:41 +0000 2012,Medical Center
4,5,-73.989658,40.740104,2.850000,Tue Apr 03 18:03:00 +0000 2012,Food Truck

(227428, 6)

dataset_TSMC2014_TKY_preprocessed.csv

,Event_ID,longitude,latitude,timestamp,Occurrence_time,Event_type
0,1,139.619590,35.705101,0.000000,Tue Apr 03 18:17:18 +0000 2012,Cosmetics Shop
1,2,139.800317,35.715581,4.766667,Tue Apr 03 18:22:04 +0000 2012,Ramen / Noodle House
2,3,139.480065,35.714542,54.816667,Tue Apr 03 19:12:07 +0000 2012,Convenience Store
3,4,139.776633,35.725592,54.916667,Tue Apr 03 19:12:13 +0000 2012,Food & Drink Shop
4,5,139.734045,35.656083,61.083333,Tue Apr 03 19:18:23 +0000 2012,Housing Development

(573703, 6)